version: '3'
services:
  db:
    ports:
      - 3306:3306
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - innodb_force_recovery=1
    volumes:
      - ./db:/var/lib/mysql
